# spring security 配置
security:
  oauth2:
    client:
      client-id: dips
      client-secret: dips
      scope: server
debug: false
logging:
  level:
    org:
      springframework:
        web: INFO
    com:
      cloud:
        gds:
          gmsanalyse: DEBUG

# 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
#    password: 12345678
    password: gov@20130528
    #数据库
    #本地数据库
#    url: jdbc:mysql://127.0.0.1:3306/magazine?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    url: jdbc:mysql://115.233.227.46:13308/gov_analyse?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

# swagger相关配置,覆盖全局配置
swagger:
  authorization:
    authorization-scope-list:
    -   scope: 'server'
        description: 'server all'
    -   scope: 'read'
        description: 'read all'
    -   scope: 'write'
        description: 'access all'
